### PR TITLE
Jade Web Page and demo enhancements

### PR DESCRIPTION
**Pull request by wtfiwtz**
Hi @decebals,

Thanks again for a wonderful enhancement to Wicket. I much prefer Jade to the other options available. 

Here is an enhancement for putting Jade on a web page itself. I have also enhanced the demo. Do you like this approach? Feel free to modify it as you see fit.

Best regards,
Nigel (@wtfiwtz)

### CODE REVIEW

**Comment by wtfiwtz** [comment]
I'll do some testing on our existing app... and then maybe enhance this with some tests too.
Cheers, Nigel

**Comment by decebals** [comment]
Hi Nigel

Sorry for delay.
I don't know if a JadeWebPage is useful. However, the initializeModel method can be removed and you can use setModelObject.

Can you give me a use case when JadeWebPage is necessary and you cannot use JadePanel? 
Which are the advantages of using JadeWebPage compared with WebPage + JadePanel?
It's possible that I don't see the big picture :)

Thanks

**Comment by wtfiwtz** [comment]
Hi @decebals,

I have most of my Wicket behaviour currently in full pages with various panels in different places. This makes my WebPage.html code very overloaded at the moment. 

By loading a JadeWebPage, I can use the 'html2jade' tool immediately to switch them over to Jade and then could potentially split up the page logic further into smaller components if required. To do that, I would then be able to take whole 'chunks' of the Jade code and move them into other files. You then adjust the indenting and you have greatly reduced the complexity in the page.

At the moment, I have to extract out all the Java code into a separate panel and do a manual conversion, which takes a long time across 50+ web pages.

I do this today with Ruby on Rails using the 'haml' and 'slim' templating languages, although its a bit easier with 'partials' in Rails. With Jade there is an 'include' directive but it doesn't work correctly at the moment (... that might be the next pull request :) ).

Cheers, Nigel

**Comment by decebals** [comment]
I look with interest at your application. Support for include can be cool
add-on.
I think that you have wicket panels in web pages. Do you want to replace
entirely the html markup with jade markup or what? What you use from wicket
in your jade approach?

**Comment by wtfiwtz** [comment]
Hi @decebals,

For us, we have a very complex application, that was built with a relatively-inexperienced team that didn't really have a good handle on how to structure the application well for organizing the code in Wicket. Effectively, the codebase has become very slow to maintain and change. If I had my time again, I would use a lot more Panels and components and put a lot less logic into the WebPages themselves.

Switching to Jade is not a complete panacea but it would allow us to better organize the code base over time, and to see what we need to clean up more quickly and readily. For example, we can see where styles have been inlined in the HTML, or work on aligning the wicket:id's so they are clearly matched between the .java and the .jade files. Also, if a particular Jade file is > 100 lines then its a good indication that we need to break it up further somehow. The main benefit is that it will help to standardize the markup so that its easier to strip out bits that have been cut'n'pasted between more than two HTML files.

So from this perspective, yes, we would like to convert all the HTML markup to Jade markup so it is clearer to see what is going on and make our application easier to maintain.

Perhaps this use-case is only for us, but I see it as highly valuable. Alternatively, if it doesn't make it into the original source then I can just maintain a separate version of wicket-jade that has this capability.

Cheers, Nigel

**Pull request closed without merging**
